version: 2
jobs:
  packer_validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate Packer Template
          command: cd packer && packer validate ./windows-2016.json
  packer_build:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Install AWS CLI & a few more tools needed for this job
          command: |
            apk -v --update add python py-pip groff less mailcap jq
            pip install --upgrade awscli
            apk -v --purge del py-pip
            rm /var/cache/apk/*
      - run:
          name: Build AMI
          command: |-
            cd packer && PACKER_LOG=1 AWS_TIMEOUT_SECONDS=600 packer build -machine-readable windows-2016.json | tee build.log
            export AMI_ID=`grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2`
            while [[ `aws ec2 describe-images --image-ids $AMI_ID --region us-east-1 | jq .Images[0].State | sed -e 's/^"//' -e 's/"$//'` != "available" ]]; \
            do \
            echo "Waiting for AMI to be available"; \
            sleep 5; \
            done
          no_output_timeout: 10m
  tf_plan:
    docker:
      - image: hashicorp/terraform:0.9.9
    working_directory: ~/terraform
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7c:38:ae:f6:80:24:59:bd:6a:b5:97:d0:e7:50:62:67"
      - run:
          name: Add GitHub to the list of trusted hosts
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Run Terraform plan
          command: |
            terraform plan-all --target circleci-windows-ami/modules/windows-ami
  tf_apply:
    docker:
      - image: hashicorp/terraform:0.9.9
    working_directory: ~/terraform
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7c:38:ae:f6:80:24:59:bd:6a:b5:97:d0:e7:50:62:67"
      - run:
          name: Add GitHub to the list of trusted hosts
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Run Terraform apply
          command: terraform apply-all --target circleci-windows-ami/modules/windows-ami
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - packer_validate:
          filters:
            branches:
              only:
                - master
      - packer_build:
          requires:
            - packer_validate
      - tf_plan:
          requires:
            - packer_build
      - tf_apply_approval:
          requires:
            - tf_plan
          type: approval
      - tf_apply:
          requires:
            - tf_apply_approval
