- hosts: win-server
  gather_facts: yes
  tasks:
  - name: Install IIS feature on {{ inventory_hostname }}
        win_feature:
        name: Web-Server
        state: present
        restart: no
        include_sub_features: yes
        include_management_tools: no

  - name: Move local web index file to {{ inventory_hostname }}
        win_copy:
        src: files/index.html
        dest: 'C:\\inetpub\\wwwroot\\index.html'

  - name: Open firewall port 80 for the IIS web server on {{ inventory_hostname }}
        win_firewall_rule:
        name: "{{ inventory_hostname }}_80"
        enable: yes
        state: present
        localport: 80
        action: Allow
        direction: In
        protocol: Tcp

  - name: Testing IIS is properly configured and running on {{ inventory_hostname }}
        win_uri:
        url: "http://{{ ansible_fqdn }}"
        return_content: yes
        register: result
        failed_when: "'Yay! Simple Ansible deployed IIS server ...' not in result.content"
